### ISSUE TITLE
NPM module does not work as configured.

### ISSUE THREAD

**Issue by timemachine3030** [pradel/ionic-push#36]
This module's package.json has: `"main": "lib/main.js",`. That file does not exist when installed as an npm dependency. 

It appears that you have a `prepublish` script that should create this file (with babel) but it is not present in the in version 1.0.0 that is available in the npm repo.

You should update this package or remove it from the npm repo as it does not work as described in the README.md file.

Thank you for you attention,

**Comment by pradel** [comment]
Hey it should be fixed in 1.0.1
